# docker-compose.yml


services:
  tts-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: tts-grpc-service:latest

    ports:
      - "50051:50051"

    env_file:
      - .env

    command: ["python", "-u", "cmd/main.py"]

    volumes:
      - .:/app

    healthcheck:

      test: ["CMD-SHELL", "grpcurl -plaintext -d '{\"text\":\"healthcheck\"}' localhost:50051 audio_service.AudioService/Synthesize"]
      interval: 30s
      timeout: 5s
      start_period: 5s
      retries: 3

    restart: on-failure
