# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import assistant_pb2 as assistant__pb2


class AssistantStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadTable = channel.unary_unary(
                '/assistant.Assistant/UploadTable',
                request_serializer=assistant__pb2.UploadTableReq.SerializeToString,
                response_deserializer=assistant__pb2.UploadTableRes.FromString,
                )
        self.Ask = channel.unary_stream(
                '/assistant.Assistant/Ask',
                request_serializer=assistant__pb2.AskReq.SerializeToString,
                response_deserializer=assistant__pb2.AskRes.FromString,
                )


class AssistantServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssistantServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadTable': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadTable,
                    request_deserializer=assistant__pb2.UploadTableReq.FromString,
                    response_serializer=assistant__pb2.UploadTableRes.SerializeToString,
            ),
            'Ask': grpc.unary_stream_rpc_method_handler(
                    servicer.Ask,
                    request_deserializer=assistant__pb2.AskReq.FromString,
                    response_serializer=assistant__pb2.AskRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'assistant.Assistant', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Assistant(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/assistant.Assistant/UploadTable',
            assistant__pb2.UploadTableReq.SerializeToString,
            assistant__pb2.UploadTableRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/assistant.Assistant/Ask',
            assistant__pb2.AskReq.SerializeToString,
            assistant__pb2.AskRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
