#src/assistant/interface/http/openapi_config.py

from fastapi.openapi.utils import get_openapi

def custom_openapi(app):
    schema = get_openapi(title=app.title, version=app.version, routes=app.routes)

    # Remove autogenerated multipart schema
    schema.get("components", {}).get("schemas", {}).pop("Body_upload_upload_post", None)

    # Patch /upload endpoint schema
    post_block = (
        schema.setdefault("paths", {})
              .setdefault("/upload", {})
              .setdefault("post", {})
    )
    post_block["requestBody"] = {
        "required": True,
        "content": {
            "multipart/form-data": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "files": {
                            "type": "array",
                            "items": {
                                "type": "string",
                                "format": "binary"
                            },
                            "description": "Upload one or more CSV/XLSX files"
                        }
                    },
                    "required": ["files"]
                },
                "encoding": {
                    "files": {
                        "style": "form",
                        "explode": False
                    }
                }
            }
        }
    }

    return schema
