# src/assistant/interface/http/openapi_config.py

from fastapi.openapi.utils import get_openapi


def custom_openapi(app):
    schema = get_openapi(title=app.title, version=app.version, routes=app.routes)

    ask_path = schema.get("paths", {}).get("/ask", {})
    if "post" in ask_path:
        ask_post = ask_path["post"]
        if "requestBody" in ask_post:
            ask_post["requestBody"]["content"]["application/json"]["examples"] = {
                "Filter by Country": {
                    "summary": "Filter rows where Country is Japan",
                    "value": {"question": "Show rows where Country is Japan"},
                },
                "Convert Currency": {
                    "summary": "Convert 100 EUR to USD",
                    "value": {
                        "question": "Convert 100 EUR to USD using the rate from 2025-01-01"
                    },
                },
                "Compare Rates": {
                    "summary": "Compare EUR and GBP",
                    "value": {
                        "question": "Compare exchange rates for EUR and GBP on 2025-01-01"
                    },
                },
                "Aggregate": {
                    "summary": "Average rate for EUR",
                    "value": {"question": "Calculate average rate to USD for EUR"},
                },
            }
    stream_path = schema.get("paths", {}).get("/ask/stream", {})
    if "post" in stream_path:
        stream_post = stream_path["post"]
        if "requestBody" in stream_post:
            stream_post["requestBody"]["content"]["application/json"]["examples"] = {
                "Filter by Country": {
                    "summary": "Filter rows where Country is Japan",
                    "value": {"question": "Show rows where Country is Japan"},
                },
                "Convert Currency": {
                    "summary": "Convert 100 EUR to USD",
                    "value": {
                        "question": "Convert 100 EUR to USD using the rate from 2025-01-01"
                    },
                },
            }

    # Remove autogenerated multipart schema
    schema.get("components", {}).get("schemas", {}).pop("Body_upload_upload_post", None)

    # Patch /upload endpoint schema
    post_block = (
        schema.setdefault("paths", {}).setdefault("/upload", {}).setdefault("post", {})
    )
    post_block["requestBody"] = {
        "required": True,
        "content": {
            "multipart/form-data": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "files": {
                            "type": "array",
                            "items": {"type": "string", "format": "binary"},
                            "description": "Upload one or more CSV/XLSX files",
                        }
                    },
                    "required": ["files"],
                },
                "encoding": {"files": {"style": "form", "explode": False}},
            }
        },
    }

    return schema
