
name: 🧪 Run Python Tests

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 📦 Checkout репозитория
      uses: actions/checkout@v3

    - name: 🐍 Установка Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: 📚 Установка зависимостей
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: 🧪 Запуск тестов
      run: |
        pytest tests/
